### ISSUE TITLE
docker-compose in README out of sync

### ISSUE THREAD

**Issue by kb2ma** [balena-labs-projects/sensor#6]
The docker-compose snippet in [`README.md`](https://github.com/balenablocks/sensor/blob/main/README.md) does not include a label for supervisor-api, but [`docker-compose.yml`](https://github.com/balenablocks/sensor/blob/main/docker-compose.yml) does. I would expect the them to be consistent.

**Comment by alanb128** [comment]
Thanks for catching that, it has been updated.
